name: Sync to Gitea

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global http.postBuffer 524288000

      - name: Debug - Print environment variables
        run: |
          echo "GITEA_URL=${{ secrets.GITEA_URL }}"
          echo "GITEA_TOKEN=${{ secrets.GITEA_TOKEN }}"
          echo "GITEA_REPO=${{ secrets.GITEA_REPO }}"
          echo "GITEA_USERNAME=${{ secrets.GITEA_USERNAME }}"

      - name: Debug - Print environment variables to ensure they're set
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_REPO: ${{ secrets.GITEA_REPO }}
          GITEA_USERNAME: ${{ secrets.GITEA_USERNAME }}
        run: |
          echo "GITEA_URL=${GITEA_URL}"
          echo "GITEA_TOKEN=${GITEA_TOKEN}"
          echo "GITEA_REPO=${GITEA_REPO}"
          echo "GITEA_USERNAME=${GITEA_USERNAME}"

      - name: Debug - Construct and print Gitea remote URL
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_REPO: ${{ secrets.GITEA_REPO }}
          GITEA_USERNAME: ${{ secrets.GITEA_USERNAME }}
        run: |
          GITEA_REMOTE_URL="https://${GITEA_USERNAME}:${GITEA_TOKEN}@${GITEA_URL}/${GITEA_USERNAME}/${GITEA_REPO}.git"
          echo "Constructed GITEA_REMOTE_URL=${GITEA_REMOTE_URL}"

      - name: Add and Push to Gitea
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_REPO: ${{ secrets.GITEA_REPO }}
          GITEA_USERNAME: ${{ secrets.GITEA_USERNAME }}
        run: |
          # Construct the Gitea remote URL
          GITEA_REMOTE_URL="https://${GITEA_USERNAME}:${GITEA_TOKEN}@${GITEA_URL}/${GITEA_USERNAME}/${GITEA_REPO}.git"
          echo "GITEA_REMOTE_URL=${GITEA_REMOTE_URL}"

          # Add the Gitea remote using the constructed URL
          git remote add gitea $GITEA_REMOTE_URL
          
          # Debug: Verify remote
          git remote -v
          
          # Fetch from Gitea to ensure connection works
          git fetch gitea

          # Push to the main branch on Gitea
          git push gitea master:main --force
