name: Sync to Gitea

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Debug: List remotes
        run: git remote -v

      - name: Debug: List branches
        run: git branch -a

      - name: Push to Gitea
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_REPO: ${{ secrets.GITEA_REPO }}
          GITEA_USERNAME: ${{ secrets.GITEA_USERNAME }}
        run: |
          # Add the Gitea remote using a token for authentication
          git remote add gitea https://$GITEA_TOKEN@$GITEA_URL/${{ secrets.GITEA_USERNAME }}/$GITEA_REPO.git
          
          # Debug: Verify remote
          git remote -v
          
          # Force push to the main branch on Gitea
          git push gitea master:main --force
